#!/usr/bin/env python3
"""Regenerate the Binance USD-M precision table from the venue.

    python3 scripts/refresh-binance-instruments.py

Writes `crates/oq-l2feed/src/venue/binance_instruments.rs`.

The table is generated into source rather than fetched at run time, and
that is deliberate. Replaying an archive has to give the same answer on
any machine on any day. A precision looked up over the network makes the
result depend on when it was run and on whether the venue was reachable,
and a tool that reads a years-old capture must not need the venue to be
up at all. A stale table is a visible problem with an obvious fix; a
table that shifts underneath a replay is neither.

Run it when a contract is listed or a precision changes. The diff is the
review: a precision that moved on a contract already captured is worth
looking at closely, because every price recorded under the old value was
read at a different scale.
"""

import datetime
import json
import pathlib
import sys
import urllib.request

URL = "https://fapi.binance.com/fapi/v1/exchangeInfo"
OUT = (
    pathlib.Path(__file__).resolve().parents[1]
    / "crates/oq-l2feed/src/venue/binance_instruments.rs"
)

HEADER = '''//! Quoting precision per contract, generated from the venue.
//!
//! Generated by `scripts/refresh-binance-instruments.py`; do not edit by
//! hand. Regenerate when a contract is listed or its precision changes:
//!
//! ```sh
//! python3 scripts/refresh-binance-instruments.py
//! ```
//!
//! Held in source rather than fetched at run time, and that is the whole
//! point. Replaying an archive has to give the same answer on any
//! machine on any day; a precision looked up over the network makes the
//! result depend on when it was run and on whether the venue was
//! reachable, and a tool that reads years-old captures must not need the
//! venue to be up. A stale table is a visible, fixable problem — a
//! table that changes underneath a replay is not.
//!
//! {count} contracts, as of {date}.

/// Price and quantity precision for `symbol`, if the venue lists it.
#[must_use]
pub fn precision(symbol: &str) -> Option<(u8, u8)> {{
    let found = match symbol {{
{arms}
        _ => return None,
    }};
    Some(found)
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn the_contracts_that_are_captured_are_present() {{
        for s in ["BTCUSDT", "ETHUSDT", "BNBUSDT", "HYPEUSDT"] {{
            assert!(precision(s).is_some(), "{{s}} is captured and must be listed");
        }}
    }}

    #[test]
    fn precisions_differ_between_contracts() {{
        // The pair that made this table necessary: replaying HYPEUSDT
        // with BTCUSDT's scale reported the archive as unreadable.
        assert_eq!(precision("BTCUSDT"), Some((2, 3)));
        assert_eq!(precision("HYPEUSDT").map(|(p, _)| p), Some(5));
    }}

    #[test]
    fn an_unlisted_symbol_is_none_rather_than_a_default() {{
        assert_eq!(precision("NOTLISTED"), None);
    }}
}}
'''


def main() -> int:
    with urllib.request.urlopen(URL, timeout=30) as response:
        payload = json.load(response)

    rows = sorted(
        (s["symbol"], s["pricePrecision"], s["quantityPrecision"])
        for s in payload["symbols"]
        if s.get("status") == "TRADING"
    )
    if not rows:
        print("refresh: the venue listed no trading contracts", file=sys.stderr)
        return 1

    # Sanity floor rather than a bare write. The venue returning a short
    # or empty list would otherwise silently replace a working table with
    # one that answers None for everything, and every tool downstream
    # would then refuse to read archives that are perfectly fine.
    if len(rows) < 100:
        print(
            f"refresh: only {len(rows)} contracts, which is too few to be real; "
            "leaving the existing table alone",
            file=sys.stderr,
        )
        return 1

    arms = "\n".join(f'        "{s}" => ({p}, {q}),' for s, p, q in rows)
    OUT.write_text(
        HEADER.format(count=len(rows), date=datetime.date.today().isoformat(), arms=arms)
    )
    print(f"wrote {OUT.relative_to(pathlib.Path.cwd())} with {len(rows)} contracts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
