#!/usr/bin/env python3
"""Regenerate the OKX swap precision table from the venue.

    python3 scripts/refresh-okx-instruments.py

Writes `crates/oq-l2feed/src/venue/okx_instruments.rs`.

Same reasoning as the Binance table: generated into source rather than
fetched at run time, because replaying an archive has to give the same
answer on any machine on any day, and a tool reading a years-old capture
must not need the venue to be up.

The two venues publish this differently, which is the whole reason each
needs its own generator rather than a shared one. Binance states
precision as a count of decimal places; OKX states a tick size and a lot
size as decimal strings, so the count has to be derived from them. A
`tickSz` of "0.1" is one decimal place, "0.00001" is five. Getting that
backwards would not fail — it would rescale every price by a power of
ten, which reads as a market that moved.
"""

import datetime
import json
import pathlib
import sys
import urllib.request

URL = "https://www.okx.com/api/v5/public/instruments?instType=SWAP"
OUT = (
    pathlib.Path(__file__).resolve().parents[1]
    / "crates/oq-l2feed/src/venue/okx_instruments.rs"
)


def decimals(step: str) -> int | None:
    """Decimal places implied by a tick or lot size such as "0.001".

    A step of "1" or "10" needs no decimals; anything with a fractional
    part needs as many places as that part is long.
    """
    step = step.strip()
    if not step:
        return None
    if "." not in step:
        return 0
    fraction = step.split(".", 1)[1].rstrip()
    return len(fraction)


HEADER = '''//! Quoting precision per contract, generated from the venue.
//!
//! Generated by `scripts/refresh-okx-instruments.py`; do not edit by
//! hand. Regenerate when a contract is listed or its tick size changes:
//!
//! ```sh
//! python3 scripts/refresh-okx-instruments.py
//! ```
//!
//! Held in source rather than fetched at run time, for the same reason
//! as the Binance table: a replay has to give the same answer on any
//! machine on any day, and a tool reading an old capture must not need
//! the venue to be reachable.
//!
//! This venue publishes a tick size and a lot size ("0.1", "0.00001")
//! where the other publishes a count of decimal places, so the count is
//! derived here. Deriving it wrongly would not fail — it would rescale
//! every price by a power of ten, which reads as a market that moved.
//!
//! Keys are this venue's own instrument ids, so the lookup happens after
//! a symbol has been translated.
//!
//! {count} contracts, as of {date}.

/// Price precision, quantity precision, and contract size for an OKX
/// instrument id, if listed.
///
/// The contract size is in units of 1e-8 of the underlying, and it is
/// the field that keeps a size on this venue comparable with a quantity
/// on one that quotes the coin: `1_000_000` means one contract is 0.01
/// of the underlying.
#[must_use]
pub fn definition(inst_id: &str) -> Option<(u8, u8, i64)> {{
    let found = match inst_id {{
{arms}
        _ => return None,
    }};
    Some(found)
}}

/// Price and quantity precision alone.
#[must_use]
pub fn precision(inst_id: &str) -> Option<(u8, u8)> {{
    let (p, q, _) = definition(inst_id)?;
    Some((p, q))
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn a_tick_size_becomes_a_count_of_decimal_places() {{
        // BTC-USDT-SWAP quotes a tick of 0.1 and a lot of 0.01, which is
        // one decimal place and two. Reading these as the venue's raw
        // sizes instead would scale every price by a factor of ten.
        assert_eq!(precision("BTC-USDT-SWAP"), Some((1, 2)));
    }}

    #[test]
    fn a_size_here_is_contracts_and_the_table_says_how_big_one_is() {{
        // 0.01 BTC per contract, in units of 1e-8 of the underlying.
        // A venue quoting the coin directly would report 100_000_000
        // for the same instrument, and the factor of a hundred between
        // them is exactly what this field exists to keep visible.
        assert_eq!(definition("BTC-USDT-SWAP"), Some((1, 2, 1_000_000)));
    }}

    #[test]
    fn an_unlisted_instrument_is_none_rather_than_a_default() {{
        assert_eq!(precision("NOT-A-SWAP"), None);
    }}
}}
'''


def main() -> int:
    # The venue rejects urllib's default User-Agent with a 403. Naming
    # the caller is both what gets through and the polite thing to do.
    request = urllib.request.Request(
        URL, headers={"User-Agent": "openquanter-refresh/1.0"}
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = json.load(response)

    if payload.get("code") != "0":
        print(f"refresh: venue returned code {payload.get('code')}", file=sys.stderr)
        return 1

    rows = []
    for r in payload.get("data", []):
        if r.get("state") != "live":
            continue
        price = decimals(r.get("tickSz", ""))
        qty = decimals(r.get("lotSz", ""))
        if price is None or qty is None:
            continue
        # A size on this venue counts contracts. ctVal is how much of
        # ctValCcy one contract is; ctMult multiplies it. Carried in
        # units of 1e-8 so it stays an integer.
        try:
            size = round(float(r["ctVal"]) * float(r.get("ctMult") or 1) * 1e8)
        except (KeyError, TypeError, ValueError):
            continue
        if size <= 0:
            continue
        rows.append((r["instId"], price, qty, size))
    rows.sort()

    # The same floor as the other generator: a short list would replace a
    # working table with one that answers None for everything, and every
    # tool downstream would then reject archives that are perfectly fine.
    if len(rows) < 50:
        print(
            f"refresh: only {len(rows)} contracts, too few to be real; "
            "leaving the existing table alone",
            file=sys.stderr,
        )
        return 1

    arms = "\n".join(f'        "{i}" => ({p}, {q}, {c}),' for i, p, q, c in rows)
    OUT.write_text(
        HEADER.format(count=len(rows), date=datetime.date.today().isoformat(), arms=arms)
    )
    print(f"wrote {OUT.name} with {len(rows)} contracts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
